EXPERIMENT:
  NAME: ""
  TAG: "BDCKD,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "BDCKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

BDCKD:
  CE_WEIGHT: 1.
  KD_WEIGHT: 0.
  BDC_WEIGHT: 0.8
  BDC_INNER_WEIGHT: 0.4
  T: 4.
