EXPERIMENT:
  NAME: ""
  TAG: "bdckd,r34,mv2"
  PROJECT: "tinyimagenet"
DATASET:
  TYPE: "tiny_imagenet"
  NUM_WORKERS: 16
DISTILLER:
  TYPE: "BDCKD"
  TEACHER: "ResNet34"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 200
  LR: 0.2
  LR_DECAY_STAGES: [60, 120, 160]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10

BDCKD:
  CE_WEIGHT: 1.
  KD_WEIGHT: 0.
  BDC_WEIGHT: 0.8
  BDC_INNER_WEIGHT: 0.
  T: 4.
